"""Harvest real sessions into fixtures and independently compute golden counts.

Never calls the adapters. Generating the golden values with the code under test
would be circular verification, and a parser bug would get baked right into the
golden. This counts with a minimal, independent counter instead.

A fixture is never overwritten once frozen. The live transcript is this very
session, so it keeps growing (observed: 798 -> 1022 records) — overwriting it
every time would move the golden along with it, making the test meaningless.
Pass --force to re-harvest.

Usage: python3 tests/harvest.py [--force]
"""
from __future__ import annotations

import collections
import json
import os
import re
import shutil
import sys

HOME = os.path.expanduser("~")
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIX = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")
SLUG = re.sub(r"[^a-zA-Z0-9]", "-", REPO)
CLAUDE_DIR = os.path.join(HOME, ".claude", "projects", SLUG)

# Pattern that strips a single top-level XML envelope from the front. Judges by
# structure rather than a tag-name list, so newly introduced tags are caught too.
_ONE_TAG = re.compile(r"^<([a-zA-Z][\w:-]*)(\s[^>]*)?>.*?</\1>\s*", re.S)

# Synthetic strings that look like human turns but weren't typed by a human.
# Only ones observed in the wild go in here.
SYNTHETIC = (
    "[Request interrupted by user]",
    "[Request interrupted by user for tool use]",
)

# <command-args> inside a slash-command envelope is what the human actually typed,
# so it's recovered. Deliberately duplicates omhc.guard's rule instead of importing
# it — if this script imported the adapter, the golden would be generated by the
# code under test, making it circular verification.
_COMMAND_ARGS = re.compile(r"<command-args>(.*?)</command-args>", re.S)


def is_envelope(text: str) -> bool:
    """Is the whole content made only of top-level XML envelopes (no prose outside tags)?"""
    rest = text.strip()
    if not rest.startswith("<"):
        return False
    while rest:
        m = _ONE_TAG.match(rest)
        if not m:
            return False
        rest = rest[m.end() :].strip()
    return True


def human_text(row: dict):
    """The text if this is human speech, else None.

    Claude Code reports tool_result as type:"user" too, so type alone isn't enough.
    Observed on this machine: of 95 user rows, subtracting 10 isMeta leaves 85, of
    which 67 are tool_result; of the remaining 19 with text, 7 are slash-command
    envelopes and command output.
    """
    if row.get("type") != "user" or row.get("isMeta") or row.get("isSidechain"):
        return None
    content = (row.get("message") or {}).get("content")
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        kinds = {b.get("type") for b in content if isinstance(b, dict)}
        if kinds != {"text"}:
            return None
        text = "".join(b.get("text", "") for b in content if b.get("type") == "text")
    else:
        return None
    if is_envelope(text):
        for body in _COMMAND_ARGS.findall(text):
            if body.strip():
                return " ".join(body.split())[:600]
        return None
    if text.strip() in SYNTHETIC:
        return None
    return text


FORCE = False


def _freeze(src: str, dst: str) -> bool:
    """Copy a fixture exactly once. Leave it alone if it already exists (unless --force).

    The live transcript keeps growing, so overwriting it would move the golden
    along with it and let regressions slip past.
    """
    if os.path.exists(dst) and not FORCE:
        return False
    shutil.copyfile(src, dst)
    return True


def _iter_json(path: str):
    with open(path, encoding="utf-8", errors="replace") as fh:
        for i, line in enumerate(fh):
            try:
                yield i, json.loads(line)
            except ValueError:
                continue


def harvest_claude() -> dict:
    tops = sorted(
        (
            os.path.join(CLAUDE_DIR, n)
            for n in os.listdir(CLAUDE_DIR)
            if n.endswith(".jsonl")
        ),
        key=os.path.getsize,
        reverse=True,
    )
    src = tops[0]
    frozen = os.path.join(FIX, "claude", "live.jsonl")
    _freeze(src, frozen)

    # Must count from the frozen copy. Counting from the live source would split the golden from the fixture.
    types: collections.Counter = collections.Counter()
    atts: collections.Counter = collections.Counter()
    first_cwd = None
    no_cwd = 0
    humans = 0
    for i, row in _iter_json(frozen):
        types[str(row.get("type"))] += 1
        if row.get("type") == "attachment":
            atts[str((row.get("attachment") or {}).get("type"))] += 1
        if row.get("cwd"):
            if first_cwd is None:
                first_cwd = i
        else:
            no_cwd += 1
        if human_text(row) is not None:
            humans += 1

    session_id = os.path.basename(src)[: -len(".jsonl")]
    sub_root = os.path.join(CLAUDE_DIR, session_id, "subagents")
    # Pick only agent-*.jsonl. journal.jsonl in the same tree is workflow
    # bookkeeping (launched/started/result), not a transcript — verifying
    # sidechain dropping needs a file carrying type:"user" isSidechain:true records.
    nested = 0
    picked = None
    for dirpath, _dirs, names in os.walk(sub_root):
        for name in sorted(names):
            if not name.endswith(".jsonl"):
                continue
            nested += 1
            if picked is None and name.startswith("agent-"):
                path = os.path.join(dirpath, name)
                if os.path.getsize(path) > 0:
                    picked = path
    if picked:
        _freeze(picked, os.path.join(FIX, "claude", "subagent.jsonl"))

    return {
        "source_name": os.path.basename(src),
        "records": sum(types.values()),
        "types": dict(types),
        "first_cwd_index": first_cwd,
        "no_cwd": no_cwd,
        "human_turns": humans,
        "attachment_subtypes": dict(atts),
        "nested_subagent_files": nested,
    }


def harvest_codex() -> dict:
    root = os.path.join(HOME, ".codex", "sessions")
    rollouts = []
    for dirpath, _dirs, names in os.walk(root):
        for name in names:
            if name.startswith("rollout-") and name.endswith(".jsonl"):
                rollouts.append(os.path.join(dirpath, name))
    if not rollouts:
        return {"records": 0, "types": {}, "cwd": None, "source_name": None}
    rollouts.sort(key=os.path.getmtime, reverse=True)
    src = rollouts[0]
    frozen = os.path.join(FIX, "codex", "exec.jsonl")
    _freeze(src, frozen)

    types: collections.Counter = collections.Counter()
    cwd = None
    for _i, row in _iter_json(frozen):
        kind = str(row.get("type"))
        if kind == "response_item":
            kind += ":" + str((row.get("payload") or {}).get("type"))
        types[kind] += 1
        if row.get("type") == "session_meta":
            cwd = (row.get("payload") or {}).get("cwd")
    return {
        "source_name": os.path.basename(src),
        "records": sum(types.values()),
        "types": dict(types),
        "cwd": cwd,
    }


def _items(path: str):
    """The items in event_msg/item_completed. Tool facts live only here (observed 0.156.1)."""
    for _i, row in _iter_json(path):
        payload = row.get("payload") or {}
        if row.get("type") == "event_msg" and payload.get("type") == "item_completed":
            item = payload.get("item")
            if isinstance(item, dict):
                yield item


def _rollouts_newest_first():
    root = os.path.join(HOME, ".codex", "sessions")
    found = []
    for dirpath, _dirs, names in os.walk(root):
        for name in names:
            if name.startswith("rollout-") and name.endswith(".jsonl"):
                found.append(os.path.join(dirpath, name))
    found.sort(key=os.path.getmtime, reverse=True)
    return found


def harvest_codex_tools() -> dict:
    """One session with a shell failure (tools.jsonl) and one file-edit session (edit.jsonl).

    exec.jsonl is already frozen as an auth-failure session and a test asserts on its
    human prompt, so it's not overwritten. Tool calls get their own separate fixtures.
    """
    wanted = {"tools": None, "edit": None}
    for path in _rollouts_newest_first():
        items = list(_items(path))
        if wanted["tools"] is None and any(
            i.get("type") == "CommandExecution" and i.get("status") == "failed"
            for i in items
        ):
            wanted["tools"] = path
        if wanted["edit"] is None and any(i.get("type") == "FileChange" for i in items):
            wanted["edit"] = path
        if all(wanted.values()):
            break

    out = {}
    for name, src in wanted.items():
        if src is None:
            out[name] = None
            continue
        frozen = os.path.join(FIX, "codex", name + ".jsonl")
        _freeze(src, frozen)
        commands, failed, changed = [], [], []
        for item in _items(frozen):
            if item.get("type") == "CommandExecution":
                argv = item.get("command") or []
                commands.append(argv[-1] if argv else "")
                if item.get("status") != "completed" or item.get("exit_code"):
                    failed.append(argv[-1] if argv else "")
            elif item.get("type") == "FileChange":
                changed.extend(sorted((item.get("changes") or {}).keys()))
        out[name] = {"source_name": os.path.basename(src), "commands": commands,
                     "failed": failed, "changed": changed}
    return out


def main(argv=None) -> int:
    global FORCE
    argv = list(sys.argv[1:] if argv is None else argv)
    FORCE = "--force" in argv
    os.makedirs(os.path.join(FIX, "claude"), exist_ok=True)
    os.makedirs(os.path.join(FIX, "codex"), exist_ok=True)
    expected = {"claude": harvest_claude(), "codex": harvest_codex(),
                "codex_tools": harvest_codex_tools()}
    with open(os.path.join(FIX, "expected.json"), "w", encoding="utf-8") as fh:
        json.dump(expected, fh, ensure_ascii=False, indent=2, sort_keys=True)
    c = expected["claude"]
    print("claude: records={} types={} first_cwd={} no_cwd={} humans={} nested={}".format(
        c["records"], len(c["types"]), c["first_cwd_index"], c["no_cwd"],
        c["human_turns"], c["nested_subagent_files"]))
    print("codex: records={} types={} cwd={}".format(
        expected["codex"]["records"], len(expected["codex"]["types"]),
        expected["codex"]["cwd"]))
    for name, got in sorted(expected["codex_tools"].items()):
        print("codex {}: {}".format(name, got and {k: got[k] for k in
                                                  ("commands", "failed", "changed")}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
